jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build
      run: ./gradlew build
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pull-request-build
        path: build/libs/
name: Build Pull Request
on:
  repository_dispatch:
    types: trigger-ga___pull-request.yml
